# Generated by Django 4.2.16 on 2024-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary School'), ('High', 'High School'), ('Varsity', 'Varsity')], max_length=10),
        ),
    ]
