# Generated by Django 4.2.16 on 2024-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_grade_name_alter_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default='Grade', max_length=50),
        ),
    ]
