# Generated by Django 4.2.16 on 2024-09-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_subject_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='topic',
        ),
    ]
